### PR TITLE
Adding the total number of people watching /r/watchpeoplecode streamers to the sidebar.

### PR DESCRIPTION
**Pull request by Chr12t0pher**
I've the function required to calculate the total number of viewers. You'd need to integrate it into the templates as I don't have access to them.

### CODE REVIEW

**Comment by paked** [comment]
Hi @Chr12t0pher, sorry I missed you on IRC earlier.

Would you like to implement the rest of this feature yourself? Or would you prefer someone with access to the templates do this (There really isn't much to the templates, and with my proposed design you wouldn't really need access to them)?

In regards to how formatting would work (which I am guessing is the part holding you back from finishing this), feel free to modify the configuration schema (but remember to implement it with environment vars as well, as they are used in production)! If this was me doing it I would create a new object in `config.json` that would look something like:

``` json
...
"info": {
  "total_views": {
    "enabled": false,
    "format" : "Currently there are {} total viewers watch WPC streams!"
  }
}
...
```

This could map to the environment vars

```
INFO_TOTAL_VIEWS_ENABLED = false
INFO_TOTAL_VIEWS_FORMAT =  "Currently there are {} total viewers watch WPC streams!"
```

You could do the same style config similar if you chose to implement stream-by-stream view totals.

Finally, just a note on abstraction: I would suggest changing the name of `get_viewers()` to `_get_total_viewers()`, and then also implementing a helper function `_get_viewers()`, which gets a single streams viewers and re-implementing `_get_total_viewers()` using that.

Thank you so much for contributing

Harrison

**Comment by Chr12t0pher** [comment]
Hi there again @paked ,

Added most of the ideas you suggested, what do you think of it now?

Chris

**Comment by paked** [comment]
@Chr12t0pher Awesome, one last thing: would you mind changing the `viewers_template` value to not be the usual `template` one?

This all looks great, and just to check it you have tested it right?

**Comment by Chr12t0pher** [comment]
@paked - Where do you mean? In the example JSON?

**Comment by paked** [comment]
@Chr12t0pher Yes, sorry

**Comment by paked** [comment]
Thanks for contributing :+1: :shipit: 

Hope to see you around the place, and hopefully contributing again!

**Pull request merged**
